#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nicely display current song from mpvctl (also in bin)
#

artist=$($HOME/bin/mpvctl -k artist)
title=$($HOME/bin/mpvctl -k title)

if [ "$artist" != null ] && [ "$title" != null ]; then
	printf '%s - %s\n' "$artist" "$title"
else
	res=$($HOME/bin/mpvctl -k filename)
	case $res in
	*'.'*)
		# must be a local file
		printf '%s\n' "$res"
		;;
	watch?v*)
		ytdl=$(youtube-dl -e "http://youtube.com/$res" 2>/dev/null)
		convert $(youtube-dl --get-thumbnail "https://www.youtube.com/$res") /tmp/image.png 2>/dev/null

		[ "$ytdl" ] && printf '%s\n' "$ytdl"

		[ -f /tmp/playing ] && touch /tmp/playing && var=$(tail -n1 /tmp/playing)

		[ "$var" = "$res" ] || notify-send -i "/tmp/image.png" "${ytdl}"
		echo "$res" >>/tmp/playing
		;;
	esac
fi
