#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nicely display current song from mpvctl (also in bin)
#

artist=$($HOME/bin/mpvctl -k artist)
title=$($HOME/bin/mpvctl -k title)
filename=$($HOME/bin/mpvctl -k filename)
[ -f /tmp/playing ] && touch /tmp/playing && current=$(tail -n1 /tmp/playing)

if [ "$artist" != null ] && [ "$title" != null ]; then
	playing=$(printf '%s - %s\n' "$artist" "$title")
	# Check if it's already playing
	[ "$current" = "$playing"] && exit
	# Print it and store it in playing
	[ "$playing" ] && printf '%s\n' "$playing" >> /tmp/playing && printf '%s\n' "$playing"
else
	res=$filename
	case $res in
	*'.'*)
		# must be a local file
		playing=$(printf '%s\n' "$res")
		# Check if it's already playing
		[ "$current" = "$playing"] && exit
		# Print it and store it in playing
		[ "$playing" ] && printf '%s\n' "$playing" >> /tmp/playing && printf '%s\n' "$playing"
		;;
	watch?v*)
		# Get url
		playing=$(youtube-dl -e "http://youtube.com/$res" 2>/dev/null)
		# Check if it's already playing
		[ "$current" = "$playing" ] && exit
		# Print it and store it in playing
		[ "$playing" ] && printf '%s\n' "$playing" >> /tmp/playing && printf '%s\n' "$playing"
		# Send A nice notification with image
		convert $(youtube-dl --get-thumbnail "https://www.youtube.com/$res") /tmp/image.png 2>/dev/null
		notify-send -i "/tmp/image.png" "${playing}"
		;;
	esac
fi
